:jsse: http://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/JSSERefGuide.html[JSSE]
:kotlin: http://kotlinlang.org/[Kotlin]


= TLS Library

Provides API for creating basic SSL/TLS connections with {jsse}. The Library is implemented in {kotlin} and is supposed to be used with, at least, Java and Kotlin.

*disclaimer*: _The current Version is not optimized for Java yet_


== Basics

=== SSL/TLS Scenarios

a) Server is authenticated by the client only +
b) Client is authenticated by server additionally to a) (*Mutual Authentication*)

.Keystore (JKS, PKCS12)

Contains private key(s) and certificate(s) used by TLS/SSL servers/clients to authenticate themselves to clients/servers.

.Truststore (JKS)

Contains certificates of trusted servers/clients or trusted CAs, no key(s) contained

== Using keytool

=== Create your own KeyStore in JKS format

1. CA Create: https://stackoverflow.com/questions/21297139/how-do-you-sign-certificate-signing-request-with-your-certification-authority

2. *Create PrivateKey:* keytool -keystore clientkeystore -genkey -alias client
*Create Certificate signing request:* keytool -keystore clientkeystore -certreq -alias client -keyalg rsa -file client.csr
3. *Sign the CSR*: openssl  x509  -req  -CA ca-certificate.pem.txt -CAkey ca-key.pem.txt -in client.csr -out client.cer  -days 365  -CAcreateserial

4. keytool -import -keystore clientkeystore -file ca-certificate.pem.txt
5. keytool –import –keystore clientkeystore –file client.cer –alias client -alias theCARoot

https://docs.oracle.com/cd/E19509-01/820-3503/6nf1il6er/

=== Creating a TrustStore

